package com.mods.combatzak.boptweaks;

import java.io.IOException;
import java.util.Map;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.eventhandler.EventBus;
import cpw.mods.fml.common.versioning.ArtifactVersion;
import cpw.mods.fml.common.versioning.VersionParser;
import cpw.mods.fml.relauncher.IFMLLoadingPlugin;
import net.minecraft.launchwrapper.Launch;
import java.util.Arrays;

/**
 * Core mod that modifies Biomes O Plenty to allow big fir tree growth
 * 
 * @author CombatZAK
 *
 */
@IFMLLoadingPlugin.Name("BoP Tweaks ASM")
@IFMLLoadingPlugin.MCVersion("1.7.10")
@IFMLLoadingPlugin.SortingIndex(2009)
//@IFMLLoadingPlugin.TransformerExclusions({ "com.mods.combatzak.boptweaks", "com.mods.combatzak.boptweaks." })
public class BoPTweaksCore implements IFMLLoadingPlugin {
	/**
	 * Indicates whether or not the runtime is obfuscated
	 */
	public static final boolean obfuscated;
	
	/**
	 * Static initializer checks for obfuscated runtime
	 */
	static {
		boolean testObfuscation = true;
		try {
			testObfuscation = Launch.classLoader.getClassBytes("net.minecraft.world.World") == null;
		}
		catch (IOException ex) {}
		obfuscated = testObfuscation;
	}
	
	/**
	 * Mod container for BoPTweaksCore
	 * @author CombatZAK
	 *
	 */
	public static class BoPTweaksContainer extends DummyModContainer {
		public static final String MODID = "boptweaks";
		public static final String MOD_NAME = "BoPTweaks";
		public static final String MOD_VERSION = "0.0.1";
		
		@Mod.Instance("boptweaks")
		public static BoPTweaksContainer instance;
		
		public BoPTweaksContainer() {
			super(new ModMetadata());

			ModMetadata metadata = super.getMetadata();
			metadata.name = MOD_NAME;
			metadata.modId = MODID;
			metadata.description = "Applies ASM update to Biomes O Plenty which allows big fir tree growth";
			metadata.version = MOD_VERSION;
			metadata.authorList = Arrays.asList(new String[] {"CombatZAK"});
			metadata.credits = "Thanks to the Biomes O Plenty team for their excellent work.";
			metadata.autogenerated = false;
			metadata.parent = "BiomesOPlenty";
			metadata.dependencies = Arrays.asList(new ArtifactVersion[] {VersionParser.parseVersionReference("BiomesOPlenty")});
			instance = this;
		}
		
		@EventHandler
		public void preInit(FMLPreInitializationEvent event) {
			if (!Loader.isModLoaded("BiomesOPlenty")) {
				throw new RuntimeException("Biomes O Plenty must also be present for BoPTweaks to work.");
			}
		}
		
		public boolean registerBus(EventBus bus, LoadController controller) {
			bus.register(this);
			return true;
		}
	}
	
	///IFMLLoadingPlugin Implementation
	
	/**
	 * Gets the set of class transformers to execute
	 */
	@Override
	public String[] getASMTransformerClass() {
		return new String[] {"com.mods.combatzak.boptweaks.asm.TransformBlockBOPSapling"};
	}

	/**
	 * Gets the mod class
	 */
	@Override
	public String getModContainerClass() {
		return "com.mods.combatzak.boptweaks.BoPTweaksCore$BoPTweaksContainer";
	}

	/**
	 * Not used
	 */
	@Override
	public String getSetupClass() {
		return null;
	}

	/**
	 * Not used
	 */
	@Override
	public void injectData(Map<String, Object> data) {
		
	}

	/**
	 * Not used
	 */
	@Override
	public String getAccessTransformerClass() {
		return null;
	}

}
